version: 2

updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directories:
      - "/assets/go/markdown-link-extractor"
      - "/assets/go/overleaf-downloader"
      - "/assets/go/website-screenshot-generator"
    schedule:
      interval: "weekly"
