name: screen capture

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  generate-screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Get list of links from markdown files
        run: go run ./assets/go/markdown-link-extractor/main.go
        working-directory: ${{ github.workspace }}

      - run: go mod download
        working-directory: ${{ github.workspace }}/assets/go/website-screenshot-generator

      - name: Generate screenshots
        run: go run ./main.go
        working-directory: ${{ github.workspace }}/assets/go/website-screenshot-generator
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITS_ALLOWED }}

      - id: vars
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: peter-evans/create-pull-request@v8.1.1
        with:
          commit-message: "content: update screenshots"
          title: "Screenshots update"
          branch: auto-act-${{ env.SHA_SHORT }}
          delete-branch: true
          labels: auto-act
          base: master
          token: ${{ secrets.COMMITS_ALLOWED }}
